"""AGENT_GUIDE.md = the hand-written playbook + a generated reference of every action."""
from . import config, registry


def _tier(a):
    return a.tier if isinstance(a.tier, str) else "depends"


def render():
    playbook = (config.HUB / "docs" / "PLAYBOOK.md").read_text(encoding="utf-8").rstrip()
    lines = [playbook, "", "## Action reference (generated by `control guide --write` — do not edit)", "",
             "MCP tool name = action name with `.` replaced by `_`.", ""]
    for area in sorted(registry.AREAS):
        info = registry.AREAS[area]
        lines += [f"### {area}", ""]
        if not info["ok"]:
            lines += [f"_Unavailable on this PC: {info['reason']}_", ""]
            continue
        lines += ["| Action | Tier | What it does |", "|---|---|---|"]
        for name in sorted(n for n, a in registry.ACTIONS.items() if a.area == area):
            a = registry.ACTIONS[name]
            first = a.help.strip().split("\n")[0].replace("|", r"\|")
            lines.append(f"| `{name}` | {_tier(a)} | {first} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write():
    path = config.HUB / "AGENT_GUIDE.md"
    path.write_text(render(), encoding="utf-8")
    return path
